CREATE TABLE IF NOT EXISTS user (
  name TEXT NOT NULL,
  pin TEXT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS duhur (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin TEXT,
  time TEXT,
  identify TEXT UNIQUE,
  FOREIGN KEY(pin) REFERENCES user(pin)
);
CREATE TABLE IF NOT EXISTS asyar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin TEXT,
  time TEXT,
  identify TEXT UNIQUE,
  FOREIGN KEY(pin) REFERENCES user(pin)
);
CREATE TABLE IF NOT EXISTS maghrib (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin TEXT,
  time TEXT,
  identify TEXT UNIQUE,
  FOREIGN KEY(pin) REFERENCES user(pin)
);
CREATE TABLE IF NOT EXISTS isya (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin TEXT,
  time TEXT,
  identify TEXT UNIQUE,
  FOREIGN KEY(pin) REFERENCES user(pin)
);
CREATE TABLE IF NOT EXISTS subuh (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin TEXT,
  time TEXT,
  identify TEXT UNIQUE,
  FOREIGN KEY(pin) REFERENCES user(pin)
);
CREATE TABLE IF NOT EXISTS tahajud (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin TEXT,
  time TEXT,
  identify TEXT UNIQUE,
  FOREIGN KEY(pin) REFERENCES user(pin)
);
